{"uuid":"071cb072-11ab-412a-a34f-856a9ebee6f3","historyId":"1feb2b9ab74a2aec42ca2f20b7bd71ac","fullName":"com.thetestingacademy.testng.assertion.MainClass.SoftAssertions","labels":[{"name":"package","value":"com.thetestingacademy.testng.assertion.MainClass"},{"name":"testClass","value":"com.thetestingacademy.testng.assertion.MainClass"},{"name":"testMethod","value":"SoftAssertions"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"LearnTestNG"},{"name":"subSuite","value":"com.thetestingacademy.testng.assertion.MainClass"},{"name":"host","value":"MBP-C02DRR20MD6M"},{"name":"thread","value":"11543@MBP-C02DRR20MD6M.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"SoftAssertions","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"The following asserts failed:\n\texpected [2] but found [1]","trace":"java.lang.AssertionError: The following asserts failed:\n\texpected [2] but found [1]\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)\n\tat org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)\n\tat com.thetestingacademy.testng.assertion.MainClass.SoftAssertions(MainClass.java:32)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:567)\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\n\tat org.testng.TestRunner.privateRun(TestRunner.java:806)\n\tat org.testng.TestRunner.run(TestRunner.java:601)\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:433)\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:330)\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1176)\n\tat org.testng.TestNG.runSuites(TestNG.java:1099)\n\tat org.testng.TestNG.run(TestNG.java:1067)\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1676692274776,"stop":1676692274780}